openapi: 3.0.0
info:
  description: This is an adaptation of Beckn core version 0.9.3
  title: One Protocol Core API
  version: 0.0.1
servers:
- url: /
paths:
  /search:
    post:
      description: Search for services by intent
      operationId: searchPOST
      requestBody:
        content:
          application/json:
            examples:
              Search by emergency service Name:
                value:
                  context:
                    domain: nic2004:85110
                    country: IND
                    city: std:080
                    action: search
                    core_version: 0.0.1
                    message_id: 85a422c4-2867-4d72-b5f5-d31588e2f7c5
                    timestamp: 2021-03-23T10:00:40.065Z
                  message:
                    intent:
                      item:
                        descriptor:
                          name: MRI Scan
            schema:
              $ref: '#/components/schemas/_search_post_request'
        description: One Protocol-Consumer Platform searches for healthcare services/product
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_search_post_200_response'
          description: Acknowledgement of message received
      tags:
      - One Protocol Provider Platform
      - One Protocol Gateway (DG)
      x-eov-operation-handler: controllers/OneProtocolProviderPlatformController
  /on_status:
    post:
      description: Fetch the status of a Service
      operationId: on_statusPOST
      requestBody:
        content:
          application/json:
            examples:
              Patient waiting:
                value:
                  context:
                    domain: nic2004:85110
                    country: IND
                    city: std:080
                    action: on_status
                    core_version: 0.0.1
                    transaction_id: 8ad631e4-01e7-44e1-a999-db41ef0ae4f6
                    message_id: 85a422c4-2867-4d72-b5f5-d31588e2f7c5
                    timestamp: 2021-03-23T10:00:40.065Z
                  message:
                    order:
                      id: "26492"
                      provider:
                        id: "1"
                        descriptor:
                          name: Provider1
                      state: PROVISIONALLY_BOOKED
                      items:
                      - id: "1"
                        descriptor:
                          name: Ambulance
                        fulfillment_id: "2"
                        provider_id: "1"
                      billing:
                        name: John Doe
                        address:
                          door: "12"
                          building: Salarpuria Greenage
                          street: "No 7, Hosur Road"
                          area_code: "560068"
                        email: john.doe@example.com
                        phone: +91-9999999999
                      fulfillment:
                        id: "2"
                        type: GENERAL-AMBULANCE
                        person:
                          id: "1"
                          name: Name1
                          image: https://image/of/person.png
                          cred: smc:13-50839
                        state:
                          descriptor:
                            code: WAITING
                        customer:
                          "./One Protocol-0_7_1.health_id": 61-8787-9274-4422
                      quote:
                        price:
                          currency: INR
                          value: "1000"
                          breakup:
                          - "./One-Protocol-0_7_1.charge": "1000"
                      payment:
                        uri: payto://ban/98273982749428?amount=INR:110&ifsc=SBIN0000575&message=hello
                        type: ON-ORDER
                        status: PAID
              Ambulance en route:
                value:
                  context:
                    domain: nic2004:85110
                    country: IND
                    city: std:080
                    action: on_status
                    core_version: 0.0.1
                    transaction_id: 8ad631e4-01e7-44e1-a999-db41ef0ae4f6
                    message_id: 85a422c4-2867-4d72-b5f5-d31588e2f7c5
                    timestamp: 2021-03-23T10:00:40.065Z
                  message:
                    order:
                      id: "26492"
                      provider:
                        id: "1"
                        descriptor:
                          name: Provider1
                      state: BOOKED
                      items:
                      - id: "1"
                        descriptor:
                          name: Ambulance
                        fulfillment_id: "2"
                        provider_id: "1"
                      billing:
                        name: John Doe
                        address:
                          door: "12"
                          building: Salarpuria Greenage
                          street: "No 7, Hosur Road"
                          area_code: "560068"
                        email: john.doe@example.com
                        phone: +91-9999999999
                      fulfillment:
                        id: "2"
                        type: GENERAL-AMBULANCE
                        person:
                          id: "1"
                          name: Name1
                          image: https://image/of/person.png
                          cred: smc:13-50839
                        state:
                          descriptor:
                            code: EN_ROUTE
                        customer:
                          "./One-Protocol-0_7_1.health_id": 61-8787-9274-4422
                      quote:
                        price:
                          currency: INR
                          value: "1000"
                          breakup:
                          - "./One-Protocol-0_7_1.charge": "1000"
                      payment:
                        uri: payto://ban/98273982749428?amount=INR:110&ifsc=SBIN0000575&message=hello
                        type: ON-ORDER
                        status: PAID
              Journey complete:
                value:
                  context:
                    domain: nic2004:85110
                    country: IND
                    city: std:080
                    action: on_status
                    core_version: 0.0.1
                    transaction_id: 8ad631e4-01e7-44e1-a999-db41ef0ae4f6
                    message_id: 85a422c4-2867-4d72-b5f5-d31588e2f7c5
                    timestamp: 2021-03-23T10:00:40.065Z
                  message:
                    order:
                      id: "26492"
                      provider:
                        id: "1"
                        descriptor:
                          name: Provider1
                      state: COMPLETED
                      items:
                      - id: "1"
                        descriptor:
                          name: Ambulance
                        fulfillment_id: "2"
                        provider_id: "1"
                      billing:
                        name: John Doe
                        address:
                          door: "12"
                          building: Salarpuria Greenage
                          street: "No 7, Hosur Road"
                          area_code: "560068"
                        email: john.doe@example.com
                        phone: +91-9999999999
                      fulfillment:
                        id: "2"
                        type: GENERAL-AMBULANCE
                        person:
                          id: "1"
                          name: Name1
                          image: https://image/of/person.png
                          cred: smc:13-50839
                        state:
                          descriptor:
                            code: FINISHED
                        customer:
                          "./One-Protocol-0_7_1.health_id": 61-8787-9274-4422
                      quote:
                        price:
                          currency: INR
                          value: "1000"
                          breakup:
                          - "./One-Protocol-0_7_1.charge": "1000"
                      payment:
                        uri: payto://ban/98273982749428?amount=INR:110&ifsc=SBIN0000575&message=hello
                        type: ON-ORDER
                        status: PAID
            schema:
              $ref: '#/components/schemas/_on_status_post_request'
        description: Describes the fulfillment status of the order
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_search_post_200_response'
          description: Acknowledgement of message received
      tags:
      - One Protocol Consumer Platform
      x-eov-operation-handler: controllers/OneProtocolConsumerPlatformController
components:
  schemas:
    Tracking:
      description: Contains tracking information that can be used by the BAP to track
        the fulfillment of an order in real-time. which is useful for knowing the
        location of time sensitive deliveries.
      properties:
        id:
          description: A unique tracking reference number
          type: string
        url:
          description: "A URL to the tracking endpoint. This can be a link to a tracking\
            \ webpage, a webhook URL created by the BAP where BPP can push the tracking\
            \ data, or a GET url creaed by the BPP which the BAP can poll to get the\
            \ tracking data. It can also be a websocket URL where the BPP can push\
            \ real-time tracking data."
          format: uri
          type: string
        location:
          allOf:
          - $ref: '#/components/schemas/Location'
          description: "In case there is no real-time tracking endpoint available,\
            \ this field will contain the latest location of the entity being tracked.\
            \ The BPP will update this value everytime the BAP calls the track API."
        status:
          description: "This value indicates if the tracking is currently active or\
            \ not. If this value is `active`, then the BAP can begin tracking the\
            \ order. If this value is `inactive`, the tracking URL is considered to\
            \ be expired and the BAP should stop tracking the order."
          enum:
          - active
          - inactive
          type: string
      type: object
    OnTrack:
      properties:
        context:
          $ref: '#/components/schemas/OnTrack_context'
        message:
          $ref: '#/components/schemas/OnTrack_message'
        error:
          $ref: '#/components/schemas/Error'
      required:
      - context
      type: object
    Track:
      properties:
        context:
          $ref: '#/components/schemas/Track_context'
        message:
          $ref: '#/components/schemas/Track_message'
      required:
      - context
      - message
      type: object
    Ack:
      description: Describes the ACK response
      example:
        status: ACK
      properties:
        status:
          description: "Describe the status of the ACK response. If schema validation\
            \ passes, status is ACK else it is NACK"
          enum:
          - ACK
          - NACK
          type: string
      required:
      - status
      type: object
    Address:
      description: Describes an address
      properties:
        door:
          description: Door / Shop number of the address
          type: string
        name:
          description: "Name of address if applicable. Example, shop name"
          type: string
        building:
          description: Name of the building or block
          type: string
        street:
          description: Street name or number
          type: string
        locality:
          description: "Name of the locality, apartments"
          type: string
        ward:
          description: Name or number of the ward if applicable
          type: string
        city:
          description: City name
          type: string
        state:
          description: State name
          type: string
        country:
          description: Country name
          type: string
        area_code:
          description: "Area code. This can be Pincode, ZIP code or any equivalent"
          type: string
      type: object
    Agent:
      allOf:
      - $ref: '#/components/schemas/Person'
      - $ref: '#/components/schemas/Contact'
      - type: object
      description: Describes an order executor
    Billing:
      description: Describes a billing event
      properties:
        name:
          description: Personal details of the customer needed for billing.
          type: string
        organization:
          $ref: '#/components/schemas/Organization'
        address:
          $ref: '#/components/schemas/Address'
        email:
          format: email
          type: string
        phone:
          type: string
        time:
          $ref: '#/components/schemas/Time'
        tax_number:
          type: string
        created_at:
          format: date-time
          type: string
        updated_at:
          format: date-time
          type: string
      required:
      - name
      - phone
      type: object
    Catalog:
      description: Describes a One Protocol-Provider catalog
      properties:
        descriptor:
          $ref: '#/components/schemas/Descriptor'
        categories:
          items:
            $ref: '#/components/schemas/Category'
          type: array
        fulfillments:
          items:
            $ref: '#/components/schemas/Fulfillment'
          type: array
        payments:
          items:
            $ref: '#/components/schemas/Payment'
          type: array
        providers:
          items:
            $ref: '#/components/schemas/Provider'
          type: array
        exp:
          description: Time after which catalog has to be refreshed
          format: date-time
          type: string
      type: object
    Category:
      description: Describes a category
      properties:
        id:
          description: Unique id of the category
          type: string
        parent_category_id:
          $ref: '#/components/schemas/Category/properties/id'
        descriptor:
          $ref: '#/components/schemas/Descriptor'
        time:
          $ref: '#/components/schemas/Time'
        tags:
          additionalProperties:
            type: string
          description: Describes a tag. This is a simple key-value store which is
            used to contain read-only metadata
          type: object
      type: object
    City:
      description: Describes a city
      properties:
        name:
          description: Name of the city
          type: string
        code:
          description: City code
          type: string
      type: object
    Contact:
      properties:
        phone:
          type: string
        email:
          type: string
        tags:
          additionalProperties:
            type: string
          description: Describes a tag. This is a simple key-value store which is
            used to contain read-only metadata
          type: object
      type: object
    Context:
      description: Describes a One Protocol message context
      properties:
        domain:
          description: Describes the domain of an object
          type: string
        country:
          $ref: '#/components/schemas/Country/properties/code'
        city:
          $ref: '#/components/schemas/City/properties/code'
        action:
          description: Defines the One Protocol API call. Any actions other than the
            enumerated actions are not supported by One Protocol Protocol
          enum:
          - search
          - select
          - init
          - confirm
          - status
          - on_search
          - on_select
          - on_init
          - on_confirm
          - on_status
          type: string
        core_version:
          description: Version of One Protocol core API specification being used
          type: string
        consumer_id:
          description: Unique id of the Consumer. By default it is the fully qualified
            domain name of the Consumer
          format: uri
          type: string
        consumer_uri:
          description: URI of the Consumer for accepting callbacks. Must have the
            same domain name as the consumer_id
          format: uri
          type: string
        provider_id:
          description: Unique id of the Provider. By default it is the fully qualified
            domain name of the Provider
          format: uri
          type: string
        provider_uri:
          description: URI of the Provider. Must have the same domain name as the
            provider_id
          format: uri
          type: string
        transaction_id:
          description: This is a unique value which persists across all API calls
            from search through confirm
          type: string
        message_id:
          description: This is a unique value which persists during a request / callback
            cycle
          type: string
        timestamp:
          description: Time of request generation in RFC3339 format
          format: date-time
          type: string
        key:
          description: The encryption public key of the sender
          type: string
        ttl:
          description: The duration in ISO8601 format after timestamp for which this
            message holds valid
          type: string
      required:
      - action
      - city
      - consumer_id
      - consumer_uri
      - core_version
      - country
      - domain
      - message_id
      - timestamp
      - transaction_id
      type: object
    Country:
      description: Describes a country.
      properties:
        name:
          description: Name of the country
          type: string
        code:
          description: Country code as per ISO 3166-1 and ISO 3166-2 format
          type: string
      type: object
    DecimalValue:
      description: Describes a decimal value
      pattern: "[+-]?([0-9]*[.])?[0-9]+"
      type: string
    Descriptor:
      description: Describes the description of a real-world object.
      properties:
        name:
          type: string
        code:
          type: string
        symbol:
          type: string
        short_desc:
          type: string
        long_desc:
          type: string
        images:
          items:
            $ref: '#/components/schemas/Image'
          type: array
        audio:
          format: uri
          type: string
        "3d_render":
          format: uri
          type: string
      type: object
    Domain:
      description: Describes the domain of an object
      type: string
    Duration:
      description: Describes duration as per ISO8601 format
      type: string
    Error:
      description: Describes an error object
      example:
        path: path
        code: code
        type: type
        message: message
      properties:
        type:
          type: string
        code:
          description: "One Protocol specific error code. For full list of error codes,\
            \ refer to error_codes.md in the root folder of this repo"
          type: string
        path:
          description: Path to json schema generating the error. Used only during
            json schema validation errors
          type: string
        message:
          description: Human readable message describing the error
          type: string
      required:
      - code
      - type
      type: object
    Fulfillment:
      description: Describes how a single product/service will be rendered/fulfilled
        to the end customer
      properties:
        id:
          description: Unique reference ID to the fulfillment of an order
          type: string
        type:
          description: This describes the type of fulfillment
          type: string
        provider_id:
          $ref: '#/components/schemas/Provider/properties/id'
        state:
          $ref: '#/components/schemas/State'
        tracking:
          default: false
          description: Indicates whether the fulfillment allows tracking
          type: boolean
        customer:
          $ref: '#/components/schemas/Fulfillment_customer'
        agent:
          $ref: '#/components/schemas/Agent'
        person:
          $ref: '#/components/schemas/Person'
        contact:
          $ref: '#/components/schemas/Contact'
        start:
          $ref: '#/components/schemas/Fulfillment_start'
        end:
          $ref: '#/components/schemas/Fulfillment_end'
        tags:
          additionalProperties:
            type: string
          description: Describes a tag. This is a simple key-value store which is
            used to contain read-only metadata
          type: object
      type: object
    Image:
      description: Image of an object. <br/><br/> A url based image will look like
        <br/><br/>```uri:http://path/to/image``` <br/><br/>
      type: string
    Intent:
      description: Intent of a user. Used for searching for services
      properties:
        descriptor:
          $ref: '#/components/schemas/Descriptor'
        provider:
          $ref: '#/components/schemas/Provider'
        fulfillment:
          $ref: '#/components/schemas/Fulfillment'
        payment:
          $ref: '#/components/schemas/Payment'
        category:
          $ref: '#/components/schemas/Category'
        item:
          $ref: '#/components/schemas/Item'
        tags:
          additionalProperties:
            type: string
          description: Describes a tag. This is a simple key-value store which is
            used to contain read-only metadata
          type: object
      type: object
    ItemQuantity:
      description: Describes count or amount of an item
      properties:
        allocated:
          $ref: '#/components/schemas/ItemQuantity_allocated'
        available:
          $ref: '#/components/schemas/ItemQuantity_allocated'
        maximum:
          $ref: '#/components/schemas/ItemQuantity_maximum'
        minimum:
          $ref: '#/components/schemas/ItemQuantity_allocated'
        selected:
          $ref: '#/components/schemas/ItemQuantity_allocated'
      type: object
    Item:
      description: Describes an item. Allows for domain extension.
      properties:
        id:
          description: This is the most unique identifier of a service item. An example
            of an Item ID could be the SKU of a product.
          format: '#/components/schemas/Item/properties/id'
          type: string
        parent_item_id:
          $ref: '#/components/schemas/Item/properties/id'
        descriptor:
          $ref: '#/components/schemas/Descriptor'
        price:
          $ref: '#/components/schemas/Price'
        category_id:
          $ref: '#/components/schemas/Category/properties/id'
        fulfillment_id:
          $ref: '#/components/schemas/Fulfillment/properties/id'
        time:
          $ref: '#/components/schemas/Time'
        matched:
          type: boolean
        related:
          type: boolean
        recommended:
          type: boolean
        tags:
          additionalProperties:
            type: string
          description: Describes a tag. This is a simple key-value store which is
            used to contain read-only metadata
          type: object
      type: object
    Language:
      description: indicates language code. One Protocol supports country codes as
        per ISO 639.2 standard
      properties:
        code:
          type: string
      type: object
    Name:
      description: "Describes the name of a person in format: ./{given_name}/{honorific_prefix}/{first_name}/{middle_name}/{last_name}/{honorific_suffix}"
      pattern: "^\\./[^/]+/[^/]*/[^/]*/[^/]*/[^/]*/[^/]*$"
      type: string
    Order:
      description: Describes the details of an order
      properties:
        id:
          description: Hash of order object without id
          type: string
        state:
          type: string
        provider:
          $ref: '#/components/schemas/_select_post_request_message_order_provider'
        items:
          items:
            $ref: '#/components/schemas/Order_items_inner'
          type: array
        billing:
          $ref: '#/components/schemas/Billing'
        fulfillment:
          $ref: '#/components/schemas/Fulfillment'
        quote:
          $ref: '#/components/schemas/Quotation'
        payment:
          $ref: '#/components/schemas/Payment'
        created_at:
          format: date-time
          type: string
        updated_at:
          format: date-time
          type: string
      type: object
    Organization:
      description: Describes an organization
      properties:
        name:
          type: string
        cred:
          type: string
      type: object
    Page:
      description: Describes a page in a search result
      properties:
        id:
          type: string
        next_id:
          type: string
      type: object
    Payment:
      description: Describes a payment
      properties:
        uri:
          description: "A payment target uri to be called by the DHP-Consumer. Supported\
            \ formats are <br></br>a) https and, <br></br>b) payto - Refer to RFC8905"
          format: uri
          type: string
        tl_method:
          enum:
          - https
          - payto
          type: string
        params:
          $ref: '#/components/schemas/Payment_params'
        type:
          description: Stage at which the payment is expected
          enum:
          - ON-ORDER
          - PRE-FULFILLMENT
          - ON-FULFILLMENT
          - POST-FULFILLMENT
          type: string
        status:
          enum:
          - PAID
          - NOT-PAID
          type: string
        time:
          $ref: '#/components/schemas/Time'
      type: object
    Person:
      description: Describes a person.
      properties:
        id:
          type: string
        name:
          description: "Describes the name of a person in format: ./{given_name}/{honorific_prefix}/{first_name}/{middle_name}/{last_name}/{honorific_suffix}"
          pattern: "^\\./[^/]+/[^/]*/[^/]*/[^/]*/[^/]*/[^/]*$"
          type: string
        image:
          description: Image of an object. <br/><br/> A url based image will look
            like <br/><br/>```uri:http://path/to/image``` <br/><br/>
          type: string
        dob:
          format: date
          type: string
        gender:
          description: "Gender of something, typically a Person, but possibly also\
            \ fictional characters, animals, etc. While Male and Female may be used,\
            \ text strings are also acceptable for people who do not identify as a\
            \ binary gender"
          type: string
        cred:
          type: string
        tags:
          additionalProperties:
            type: string
          description: Describes a tag. This is a simple key-value store which is
            used to contain read-only metadata
          type: object
      required:
      - name
      type: object
    Policy:
      description: Describes a policy. Allows for domain extension.
      properties:
        id:
          type: string
        descriptor:
          $ref: '#/components/schemas/Descriptor'
        parent_policy_id:
          $ref: '#/components/schemas/Policy/properties/id'
        time:
          $ref: '#/components/schemas/Time'
      type: object
    Price:
      description: Describes the price of an item. Allows for domain extension.
      properties:
        currency:
          type: string
        value:
          description: Describes a decimal value
          pattern: "[+-]?([0-9]*[.])?[0-9]+"
          type: string
        estimated_value:
          description: Describes a decimal value
          pattern: "[+-]?([0-9]*[.])?[0-9]+"
          type: string
        computed_value:
          description: Describes a decimal value
          pattern: "[+-]?([0-9]*[.])?[0-9]+"
          type: string
        listed_value:
          description: Describes a decimal value
          pattern: "[+-]?([0-9]*[.])?[0-9]+"
          type: string
        offered_value:
          description: Describes a decimal value
          pattern: "[+-]?([0-9]*[.])?[0-9]+"
          type: string
        minimum_value:
          description: Describes a decimal value
          pattern: "[+-]?([0-9]*[.])?[0-9]+"
          type: string
        maximum_value:
          description: Describes a decimal value
          pattern: "[+-]?([0-9]*[.])?[0-9]+"
          type: string
      type: object
    Provider:
      description: "Describes a service provider. This can be a restaurant, a hospital,\
        \ a Store etc"
      properties:
        id:
          description: Id of the provider
          type: string
        descriptor:
          $ref: '#/components/schemas/Descriptor'
        category_id:
          description: Category Id of the provider
          type: string
        time:
          $ref: '#/components/schemas/Time'
        categories:
          items:
            $ref: '#/components/schemas/Category'
          type: array
        fulfillments:
          items:
            $ref: '#/components/schemas/Fulfillment'
          type: array
        payments:
          items:
            $ref: '#/components/schemas/Payment'
          type: array
        items:
          items:
            $ref: '#/components/schemas/Item'
          type: array
        exp:
          description: Time after which catalog has to be refreshed
          format: date-time
          type: string
        tags:
          additionalProperties:
            type: string
          description: Describes a tag. This is a simple key-value store which is
            used to contain read-only metadata
          type: object
      type: object
    Quotation:
      description: Describes a quote
      properties:
        price:
          $ref: '#/components/schemas/Price'
        breakup:
          items:
            $ref: '#/components/schemas/Quotation_breakup_inner'
          type: array
        ttl:
          description: Describes duration as per ISO8601 format
          type: string
      type: object
    Scalar:
      description: An object representing a scalar quantity.
      properties:
        type:
          enum:
          - CONSTANT
          - VARIABLE
          type: string
        value:
          type: number
        estimated_value:
          type: number
        computed_value:
          type: number
        range:
          $ref: '#/components/schemas/Scalar_range'
        unit:
          type: string
      required:
      - unit
      - value
      type: object
    Schedule:
      description: Describes a schedule
      properties:
        frequency:
          description: Describes duration as per ISO8601 format
          type: string
        holidays:
          items:
            format: date-time
            type: string
          type: array
        times:
          items:
            format: date-time
            type: string
          type: array
      type: object
    State:
      description: Describes a state
      properties:
        descriptor:
          $ref: '#/components/schemas/Descriptor'
        updated_at:
          format: date-time
          type: string
        updated_by:
          description: ID of entity which changed the state
          type: string
      type: object
    Subscriber:
      description: "Any entity which wants to authenticate itself on a network. This\
        \ can be a One Protocol-Consumer, One Protocol-Provider, DG."
      properties:
        subscriber_id:
          description: Registered domain name of the subscriber. Must have a valid
            SSL certificate issued by a Certificate Authority of the operating region
          type: string
        type:
          enum:
          - consumer
          - provider
          - gateway
          type: string
        cb_url:
          description: Callback URL of the subscriber. The Registry will call this
            URL's on_subscribe API to validate the subscriber\'s credentials
          type: string
        domain:
          description: Describes the domain of an object
          type: string
        city:
          $ref: '#/components/schemas/City/properties/code'
        country:
          $ref: '#/components/schemas/Country/properties/code'
        signing_public_key:
          description: "Signing Public key of the subscriber. <br/><br/>Any subscriber\
            \ platform (dhp_consumer, dhp_provider, dg) who wants to transact on the\
            \ network must digitally sign the ```requestBody``` using the corresponding\
            \ private key of this public key and send it in the transport layer header.\
            \ In case of ```HTTP``` it is the ```Authorization``` header. <br><br/>The\
            \ ```Authorization``` will be used to validate the signature of a dhp_consumer\
            \ or dhp_provider.<br/><br/>Furthermore, if an API call is being proxied\
            \ or multicast by a One Protocol Gateway, the BG must use it\\'s signing\
            \ key to digitally sign the ```requestBody``` using the corresponding\
            \ private key of this public key and send it in the ```Proxy-Authorization```\
            \ header."
          type: string
        encryption_public_key:
          description: Encryption public key of the dhp_consumer subscriber. Any dhp_provider
            must encrypt the ```requestBody.message``` value of the ```on_search```
            API using this public key.
          type: string
        status:
          enum:
          - INITIATED
          - UNDER_SUBSCRIPTION
          - SUBSCRIBED
          - INVALID_SSL
          - UNSUBSCRIBED
          type: string
        created:
          description: Timestamp when a subscriber was added to the registry with
            status = INITIATED
          format: date-time
          type: string
        updated:
          format: date-time
          type: string
        expires:
          description: Expiry timestamp in UTC derived from the ```lease_time``` of
            the subscriber
          format: date-time
          type: string
      type: object
    Tags:
      additionalProperties:
        type: string
      description: Describes a tag. This is a simple key-value store which is used
        to contain read-only metadata
      type: object
    Time:
      description: Describes time in its various forms. It can be a single point in
        time; duration; or a structured timetable of operations
      properties:
        label:
          type: string
        timestamp:
          format: date-time
          type: string
        duration:
          description: Describes duration as per ISO8601 format
          type: string
        range:
          $ref: '#/components/schemas/Time_range'
        days:
          description: comma separated values representing days of the week
          type: string
        schedule:
          $ref: '#/components/schemas/Schedule'
      type: object
    _search_post_request_message:
      properties:
        intent:
          $ref: '#/components/schemas/Intent'
      type: object
    _search_post_request:
      properties:
        context:
          $ref: '#/components/schemas/Context'
        message:
          $ref: '#/components/schemas/_search_post_request_message'
      required:
      - context
      - message
      type: object
    _search_post_200_response_message:
      example:
        ack:
          status: ACK
      properties:
        ack:
          $ref: '#/components/schemas/Ack'
      required:
      - ack
      type: object
    _search_post_200_response:
      example:
        message:
          ack:
            status: ACK
        error:
          path: path
          code: code
          type: type
          message: message
      properties:
        message:
          $ref: '#/components/schemas/_search_post_200_response_message'
        error:
          $ref: '#/components/schemas/Error'
      required:
      - message
      type: object
    _select_post_request_message_order_provider:
      properties:
        id:
          $ref: '#/components/schemas/Provider/properties/id'
      type: object
    _select_post_request_message_order_items_inner:
      properties:
        id:
          $ref: '#/components/schemas/Item/properties/id'
        quantity:
          $ref: '#/components/schemas/ItemQuantity/properties/selected'
        fulfillment_id:
          $ref: '#/components/schemas/Fulfillment/properties/id'
      required:
      - id
      type: object
    _select_post_request_message_order:
      properties:
        provider:
          $ref: '#/components/schemas/_select_post_request_message_order_provider'
        items:
          items:
            $ref: '#/components/schemas/_select_post_request_message_order_items_inner'
          type: array
      type: object
    _select_post_request_message:
      properties:
        order:
          $ref: '#/components/schemas/_select_post_request_message_order'
      required:
      - order
      type: object
    _select_post_request:
      properties:
        context:
          $ref: '#/components/schemas/Context'
        message:
          $ref: '#/components/schemas/_select_post_request_message'
      required:
      - context
      - message
      type: object
    _init_post_request_message_order:
      properties:
        provider:
          $ref: '#/components/schemas/_select_post_request_message_order_provider'
        items:
          items:
            $ref: '#/components/schemas/_select_post_request_message_order_items_inner'
          type: array
        billing:
          $ref: '#/components/schemas/Billing'
        fulfillment:
          $ref: '#/components/schemas/Fulfillment'
        quote:
          $ref: '#/components/schemas/Quotation'
      type: object
    _init_post_request_message:
      properties:
        order:
          $ref: '#/components/schemas/_init_post_request_message_order'
      required:
      - order
      type: object
    _init_post_request:
      properties:
        context:
          $ref: '#/components/schemas/Context'
        message:
          $ref: '#/components/schemas/_init_post_request_message'
      required:
      - context
      - message
      type: object
    _confirm_post_request_message_order:
      properties:
        provider:
          $ref: '#/components/schemas/_select_post_request_message_order_provider'
        state:
          $ref: '#/components/schemas/State'
        items:
          items:
            $ref: '#/components/schemas/_select_post_request_message_order_items_inner'
          type: array
        billing:
          $ref: '#/components/schemas/Billing'
        fulfillment:
          $ref: '#/components/schemas/Fulfillment'
      type: object
    _confirm_post_request_message:
      properties:
        order:
          $ref: '#/components/schemas/_confirm_post_request_message_order'
      required:
      - order
      type: object
    _confirm_post_request:
      properties:
        context:
          $ref: '#/components/schemas/Context'
        message:
          $ref: '#/components/schemas/_confirm_post_request_message'
      required:
      - context
      - message
      type: object
    _status_post_request_message:
      properties:
        order_id:
          $ref: '#/components/schemas/Order/properties/id'
      required:
      - order_id
      type: object
    _status_post_request:
      properties:
        context:
          $ref: '#/components/schemas/Context'
        message:
          $ref: '#/components/schemas/_status_post_request_message'
      required:
      - context
      - message
      type: object
    _on_search_post_request_message:
      properties:
        catalog:
          $ref: '#/components/schemas/Catalog'
      required:
      - catalog
      type: object
    _on_search_post_request:
      properties:
        context:
          $ref: '#/components/schemas/Context'
        message:
          $ref: '#/components/schemas/_on_search_post_request_message'
        error:
          $ref: '#/components/schemas/Error'
      required:
      - context
      type: object
    _on_search_post_200_response:
      example:
        message:
          ack:
            status: ACK
        error:
          path: path
          code: code
          type: type
          message: message
      properties:
        message:
          $ref: '#/components/schemas/_search_post_200_response_message'
        error:
          $ref: '#/components/schemas/Error'
      required:
      - context
      type: object
    _on_select_post_request_message_order:
      properties:
        provider:
          $ref: '#/components/schemas/Provider'
        items:
          items:
            $ref: '#/components/schemas/_select_post_request_message_order_items_inner'
          type: array
        quote:
          $ref: '#/components/schemas/Quotation'
      type: object
    _on_select_post_request_message:
      properties:
        order:
          $ref: '#/components/schemas/_on_select_post_request_message_order'
      required:
      - order
      type: object
    _on_select_post_request:
      properties:
        context:
          $ref: '#/components/schemas/Context'
        message:
          $ref: '#/components/schemas/_on_select_post_request_message'
        error:
          $ref: '#/components/schemas/Error'
      required:
      - context
      type: object
    _on_init_post_request_message_order_items_inner:
      properties:
        id:
          $ref: '#/components/schemas/Item/properties/id'
        quantity:
          $ref: '#/components/schemas/ItemQuantity/properties/selected'
      type: object
    _on_init_post_request_message_order:
      properties:
        id:
          $ref: '#/components/schemas/Order/properties/id'
        provider:
          $ref: '#/components/schemas/_select_post_request_message_order_provider'
        state:
          $ref: '#/components/schemas/State'
        items:
          items:
            $ref: '#/components/schemas/_on_init_post_request_message_order_items_inner'
          type: array
        billing:
          $ref: '#/components/schemas/Billing'
        fulfillment:
          $ref: '#/components/schemas/Fulfillment'
        quote:
          $ref: '#/components/schemas/Quotation'
        payment:
          $ref: '#/components/schemas/Payment'
      type: object
    _on_init_post_request_message:
      properties:
        order:
          $ref: '#/components/schemas/_on_init_post_request_message_order'
      required:
      - order
      type: object
    _on_init_post_request:
      properties:
        context:
          $ref: '#/components/schemas/Context'
        message:
          $ref: '#/components/schemas/_on_init_post_request_message'
        error:
          $ref: '#/components/schemas/Error'
      required:
      - context
      type: object
    _on_status_post_request_message:
      properties:
        order:
          $ref: '#/components/schemas/Order'
      required:
      - order
      type: object
    _on_status_post_request:
      properties:
        context:
          $ref: '#/components/schemas/Context'
        message:
          $ref: '#/components/schemas/_on_status_post_request_message'
        error:
          $ref: '#/components/schemas/Error'
      required:
      - context
      type: object
    Fulfillment_customer:
      properties:
        person:
          $ref: '#/components/schemas/Person'
        contact:
          $ref: '#/components/schemas/Contact'
      type: object
    Fulfillment_start:
      description: Details on the start of fulfillment
      properties:
        time:
          $ref: '#/components/schemas/Time'
        instructions:
          $ref: '#/components/schemas/Descriptor'
        contact:
          $ref: '#/components/schemas/Contact'
        person:
          $ref: '#/components/schemas/Person'
      type: object
    Fulfillment_end:
      description: Details on the end of fulfillment
      properties:
        time:
          $ref: '#/components/schemas/Time'
        instructions:
          $ref: '#/components/schemas/Descriptor'
        contact:
          $ref: '#/components/schemas/Contact'
        person:
          $ref: '#/components/schemas/Person'
      type: object
    ItemQuantity_allocated:
      properties:
        count:
          minimum: 0
          type: integer
        measure:
          $ref: '#/components/schemas/Scalar'
      type: object
    ItemQuantity_maximum:
      properties:
        count:
          minimum: 1
          type: integer
        measure:
          $ref: '#/components/schemas/Scalar'
      type: object
    Order_items_inner:
      properties:
        id:
          $ref: '#/components/schemas/Item/properties/id'
        quantity:
          $ref: '#/components/schemas/ItemQuantity/properties/selected'
      required:
      - id
      type: object
    Payment_params:
      additionalProperties:
        type: string
      properties:
        transaction_id:
          description: This value will be placed in the the $transaction_id url param
            in case of http/get and in the requestBody http/post requests
          type: string
        transaction_status:
          type: string
        amount:
          description: "Rating value given to the object. This can be a single value\
            \ or can also contain an inequality operator like gt, gte, lt, lte. This\
            \ can also contain an inequality expression containing logical operators\
            \ like && and ||."
          type: string
        currency:
          $ref: '#/components/schemas/Price/properties/currency'
      required:
      - currency
      type: object
    Quotation_breakup_inner:
      properties:
        title:
          type: string
        price:
          $ref: '#/components/schemas/Price'
      type: object
    Scalar_range:
      properties:
        min:
          type: number
        max:
          type: number
      type: object
    Time_range:
      properties:
        start:
          format: date-time
          type: string
        end:
          format: date-time
          type: string
      type: object
    Location:
      description: The physical location of something
      properties:
        id:
          type: string
        descriptor:
          $ref: '#/components/schemas/Descriptor_1'
        map_url:
          description: The url to the map of the location. This can be a globally
            recognized map url or the one specified by the network policy.
          format: uri
          type: string
        gps:
          allOf:
          - $ref: '#/components/schemas/Gps'
          description: The GPS co-ordinates of this location.
        address:
          allOf:
          - $ref: '#/components/schemas/Address_1'
          description: The address of this location.
        city:
          allOf:
          - $ref: '#/components/schemas/City'
          description: "The city this location is, or is located within"
        district:
          description: "The state this location is, or is located within"
          type: string
        state:
          allOf:
          - $ref: '#/components/schemas/State_1'
          description: "The state this location is, or is located within"
        country:
          allOf:
          - $ref: '#/components/schemas/Country_1'
          description: "The country this location is, or is located within"
        area_code:
          type: string
        circle:
          $ref: '#/components/schemas/Circle'
        polygon:
          description: The boundary polygon of this location
          type: string
        "3dspace":
          description: The three dimensional region describing this location
          type: string
        rating:
          allOf:
          - $ref: '#/components/schemas/value'
          description: The rating of this location
      type: object
    Descriptor_1:
      description: Physical description of something.
      properties:
        name:
          type: string
        code:
          type: string
        short_desc:
          type: string
        long_desc:
          type: string
        additional_desc:
          $ref: '#/components/schemas/Descriptor_1_additional_desc'
        media:
          items:
            $ref: '#/components/schemas/MediaFile'
          type: array
        images:
          items:
            $ref: '#/components/schemas/Image_1'
          type: array
      type: object
    Gps:
      description: Describes a GPS coordinate
      pattern: "^[-+]?([1-8]?\\d(\\.\\d+)?|90(\\.0+)?),\\s*[-+]?(180(\\.0+)?|((1[0-7]\\\
        d)|([1-9]?\\d))(\\.\\d+)?)$"
      type: string
    Address_1:
      description: Describes a postal address.
      type: string
    State_1:
      description: A bounded geopolitical region of governance inside a country.
      properties:
        name:
          description: Name of the state
          type: string
        code:
          description: State code as per country or international standards
          type: string
      type: object
    Country_1:
      description: Describes a country
      properties:
        name:
          description: Name of the country
          type: string
        code:
          description: Country code as per ISO 3166-1 and ISO 3166-2 format
          type: string
      type: object
    Circle:
      description: Describes a circular region of a specified radius centered at a
        specified GPS coordinate.
      properties:
        gps:
          description: Describes a GPS coordinate
          pattern: "^[-+]?([1-8]?\\d(\\.\\d+)?|90(\\.0+)?),\\s*[-+]?(180(\\.0+)?|((1[0-7]\\\
            d)|([1-9]?\\d))(\\.\\d+)?)$"
          type: string
        radius:
          $ref: '#/components/schemas/Scalar_1'
      type: object
    value:
      description: "Rating value given to the object. This can be a single value or\
        \ can also contain an inequality operator like gt, gte, lt, lte. This can\
        \ also contain an inequality expression containing logical operators like\
        \ && and ||."
      type: string
    MediaFile:
      description: This object contains a url to a media file.
      properties:
        mimetype:
          description: "indicates the nature and format of the document, file, or\
            \ assortment of bytes. MIME types are defined and standardized in IETF's\
            \ RFC 6838"
          type: string
        url:
          description: The URL of the file
          format: uri
          type: string
        signature:
          description: The digital signature of the file signed by the sender
          type: string
        dsa:
          description: The signing algorithm used by the sender
          type: string
      type: object
    Image_1:
      description: Describes an image
      properties:
        url:
          description: URL to the image. This can be a data url or an remote url
          format: uri
          type: string
        size_type:
          description: The size of the image. The network policy can define the default
            dimensions of each type
          enum:
          - xs
          - sm
          - md
          - lg
          - xl
          - custom
          type: string
        width:
          description: Width of the image in pixels
          type: string
        height:
          description: Height of the image in pixels
          type: string
      type: object
    Scalar_1:
      description: Describes a scalar
      properties:
        type:
          enum:
          - CONSTANT
          - VARIABLE
          type: string
        value:
          description: Describes a numerical value in decimal form
          pattern: "[+-]?([0-9]*[.])?[0-9]+"
          type: string
        estimated_value:
          description: Describes a numerical value in decimal form
          pattern: "[+-]?([0-9]*[.])?[0-9]+"
          type: string
        computed_value:
          description: Describes a numerical value in decimal form
          pattern: "[+-]?([0-9]*[.])?[0-9]+"
          type: string
        range:
          $ref: '#/components/schemas/Scalar_1_range'
        unit:
          type: string
      type: object
    DecimalValue_1:
      description: Describes a numerical value in decimal form
      pattern: "[+-]?([0-9]*[.])?[0-9]+"
      type: string
    OnTrack_context:
      allOf:
      - $ref: '#/components/schemas/Context'
      - properties:
          action:
            enum:
            - on_track
            type: string
        required:
        - action
    OnTrack_message:
      properties:
        tracking:
          $ref: '#/components/schemas/Tracking'
      required:
      - tracking
      type: object
    Track_context:
      allOf:
      - $ref: '#/components/schemas/Context'
      - properties:
          action:
            enum:
            - track
            type: string
        required:
        - action
    Track_message:
      properties:
        order_id:
          $ref: '#/components/schemas/Order/properties/id'
        callback_url:
          format: uri
          type: string
      required:
      - order_id
      type: object
    Descriptor_1_additional_desc:
      properties:
        url:
          type: string
        content_type:
          enum:
          - text/plain
          - text/html
          - application/json
          type: string
      type: object
    Scalar_1_range:
      properties:
        min:
          description: Describes a numerical value in decimal form
          pattern: "[+-]?([0-9]*[.])?[0-9]+"
          type: string
        max:
          description: Describes a numerical value in decimal form
          pattern: "[+-]?([0-9]*[.])?[0-9]+"
          type: string
      type: object
